title: __WIP__
author: UserNombre

url: "https://usernombre.github.io"
baseurl: ""
permalink: "/:year/:month/:title:output_ext"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled: all
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"
